# Generated by Django 3.2.13 on 2022-09-25 03:16

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora modificado')),
                ('desactivate_at', models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora desativado')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['title'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'db_table': 'todos',
            },
        ),
    ]
